### ISSUE TITLE
Feature request: Non-editor mode

### ISSUE THREAD

**Issue by 3rd** [Kharacternyk/klunok#4]
Hey, thanks for building this!
It would be great to disable the whole editor / process matching part, and backup all changes based on included/excluded globs.
Is such a mode on the roadmap?

**Comment by 3rd** [comment]
Sorry, just saw it's possible. Got confused by `included_paths` vs `cluded_paths`.

**Comment by 3rd** [comment]
Re-opening for globs in excluded_paths, is there a built-in way to filter out patterns of files?
Something like https://docs.syncthing.net/users/ignoring.html
If not, is there a way to provide a dynamic `excluded_paths` that gets evaluated every time to handle it manually?

**Comment by Kharacternyk** [comment]
There is no glob support as of now. What kind of patterns do you need to ignore? Are they based on file extensions?

**Comment by 3rd** [comment]
Ideally I'd love for it to backup everything inside a big directory which includes projects, config, files, artifacts, regardless of the editing program. I think that will work with `included_paths`, but I'd like to filter out all `target`, `build`, `dist` directories, that could be at any level.
A nice way to do it would be if it could support filter functions in the config:
```lua
_G.excluded_paths_filter = function(path)
  if ... then return true end
end
```

**Comment by Kharacternyk** [comment]
Callbacks in the config would be a nice feature. However, even though I appreciate that you use Klunok, I don't really see why you would prefer it to the traditional backup solutions for your use case. The editor detection is the core feature of Klunok, and if you don't use it, you are left only with drawbacks such as the sudo requirement.

**Comment by 3rd** [comment]
I want the kind of micro versioning Klunok offers, something that does a 5 min debounced "auto-commit", I'd probably be able to make some git-based contraption, but another limitation I have is that it must be Syncthing-friendly, and Syncthing breaks git repos sadly.
But I get that's not the focus for Klunok, thanks for making it, it's a very interesting thing. I'll draw some inspiration from it and try to do something smaller for my use case!

**Comment by Kharacternyk** [comment]
> I'll draw some inspiration from it and try to do something smaller for my use case!

If you end up sharing you project, I would love to reference it in the documentation, so that people with use cases similar to your one could consider your project as a better fit for them than Klunok.
